### ISSUE TITLE
[Bugs] sort apps by usage

### ISSUE THREAD

**Issue by l2eused** [LinkSheet/LinkSheet#125]
### Bug description

I already disable **sort apps by usage**. it should always sort by package name or app name.
But when I tried to open same link, it show previous open app in top of list.

I disable **last picked app** too.

### Version

master-0e61ad6-nightly

### Device

Xiaomi Mi9

### Android version

Android 10

### Reproducible on latest nightly build

No

**Comment by 1fexd** [comment]
Hi, "Sort apps by usage" uses the Android system usage stats, it has nothing todo with the actual LinkSheet app selection history. Currently, the apps are sorted as follows (sorting applied in the following order):

1. LinkSheet selection history
2. Android usage stats (if enabled)
3. App name

A fine grained sort editor will be implemented at a later point in time via #106. I was not able to reproduce the issue with "Never show last picked app section"
