### ISSUE TITLE
[0.0.11] URL with included username and password mangled

### ISSUE THREAD

**Issue by SA-Flipperwaldt** [LinkSheet/LinkSheet#20]
"http://usern:passwrd@192.168.0.227" arrives in browser as "http://192.168.0.227d@192.168.0.227"

I matched the character count of the actual username and password in this example, because I think the "d" left before the @ symbol is a clue.

Used to work fine in previous versions.

I'm no coder, but I suspect there possibly is some regex issue somewhere with the code to lowercase the hostname. Something like that.

Otherwise very neat app, very useful to me. Thanks for your efforts.

**Comment by 1fexd** [comment]
Hi, thanks for reporting this bug. Can you test if it has been properly fixed in [0.0.16](https://github.com/1fexd/LinkSheet/releases/tag/0.0.16-debug)?

**Comment by SA-Flipperwaldt** [comment]
I only have one specific case to test it against, but that seems to work now. Thank you, awesome!

I'm not familiar with etiquette here, so I don't know if I should hit the close issue button myself, but as far as I'm concerned we're good. Thanks again.
