### ISSUE TITLE
Can not translate `minutes` in `donate_card_subtitle`

### ISSUE THREAD

**Issue by juliazero** [LinkSheet/LinkSheet#216]
### Bug description

Hello, it is currently impossible to translate `minutes`, `hours`, `days` etc. in key `donate_card_subtitle`.

Example in this screenshot it show `45 minutes` instead `45 minut` (Polish).
<img src=https://github.com/1fexd/LinkSheet/assets/11527277/18dc5813-9c3b-40c0-8ccc-edacdd602445 width=30%>

It is also not possible to use pluralization.
If the message will be displayed after 2 minutes, `2 minuty` (Polish) should be used.

Plurals in Polish with this message context:
- You are using LinkSheet for minutes:
-- One (1) minutę
-- Few (2-4) minuty
-- Many (5-...): minut

- You are using LinkSheet for hours:
-- One (1) godzinę
-- Few (2-4) godziny
-- Many (5-...): godzin

- You are using LinkSheet for days:
-- One (1) dzień
-- Few (2-...) dni
-- Many (5-...) dni

Weblate should handle pluralization automatically if seconds, minutes, hours, days, etc. are separated from %s.

For English, it is just `one`, `other`

- You are using LinkSheet for minutes:
-- One (1) minute
-- Other (2-...) minutes

Etc.

This is not a big deal. You can also simplify this information to:
- Do you like this app? Leave a star on github and/or make a donation.

Short, concise and to the point.

But I leave the decision to you, of course :)

### Version

HEAD-fbaaafa-release_debug

### Device

OnePlus 8T

### Android version

Android 13 (custom)

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
> If the message will be displayed after 2 minutes, `2 minuty` (Polish) should be used.

Thanks for the hint, will add translation support for that.

> But I leave the decision to you, of course :)

To be fair, I like to point how many hours I spent on this app just to let the user know this is not something some can hack together on a weekend

**Comment by 1fexd** [comment]
I just checked and and LinkSheet does use pluralization? Is the problem that you can't that file through Weblate?
