### ISSUE TITLE
feature(1.1.0): Add language selector

### ISSUE THREAD

**Issue by Daviteusz** [LinkSheet/LinkSheet#229]
### Feature description

Users should have the option to choose a language other than the one set in the system.

Example language selector:
<img src=https://github.com/1fexd/LinkSheet/assets/11527277/d349767a-910c-484a-bb40-b0e07007f9cc width=30%>

**Comment by 1fexd** [comment]
This has been available via the Android app settings for quite some time now, so I'm closing this.
