### ISSUE TITLE
Block Domains (SECURITY)

### ISSUE THREAD

**Issue by saltsoftdrink** [LinkSheet/LinkSheet#244]
### Feature description

Make a new feature where I can disable this types link I mean just the web name like this I've mentioned or example hacking.com where it will show site is disabled I mean it should not go to the sites & **THIS IS A BIG STEP FOR SECURITY** like how people get fake message msgs of getting money they just click on it

![Screenshot_2023-11-16-03-30-33-43_338d1168706d12c5c38fa9d3a60e24f4](https://github.com/1fexd/LinkSheet/assets/88429776/851717d1-1046-4f92-8d0b-a8773be417c1)
![Screenshot_2023-11-16-03-30-29-88_f9ee0578fe1cc94de7482bd41accb329](https://github.com/1fexd/LinkSheet/assets/88429776/bd601e15-f894-4c69-ae22-f81fece6a3ef)

**Comment by 1fexd** [comment]
I have no clue what you are saying, could you please just use Google translate?

**Comment by 1fexd** [comment]
I'm sorry but I still don't get what it is that you want.
