### ISSUE TITLE
fix(1.0.0): Can't login to Samsung Health when LinkSheet is default browser

### ISSUE THREAD

**Issue by xmha97** [LinkSheet/LinkSheet#251]
### Feature description

![Screenshot_2023-11-25-04-18-54-225_com android chrome](https://github.com/1fexd/LinkSheet/assets/23485114/4dd14048-2ef3-447a-b189-95bced29dee8)

**Comment by 1fexd** [comment]
What app is that?

**Comment by tberghuis** [comment]
happened for me with "Samsung Health" and "Galaxy Watch4 Manager". 

Is there a setting in link sheet to disable for specific domains? (I had to uninstall to login)

**Comment by 1fexd** [comment]
> happened for me with "Samsung Health" and "Galaxy Watch4 Manager". 

Could you please provide a logfile?

> Is there a setting in link sheet to disable for specific domains? (I had to uninstall to login)

Nope

**Comment by SodaWithoutSparkles** [comment]
try going to settings > privacy and turn the referrer off

**Comment by 1fexd** [comment]
> try going to settings > privacy and turn the referrer off

Does this fix the error?

**Comment by 1fexd** [comment]
This has been stale for quite some time - please open a new issue if the bug is still present.
