### ISSUE TITLE
feature(1.1.0): Allow hiding "once" "always" buttons on browser links

### ISSUE THREAD

**Issue by firefoxlover** [LinkSheet/LinkSheet#291]
### Feature description

Awesome app! I will donate soon. It is such a useful feature.

I always seperate my browser usage, so it is redundant to ask "once" "always" on links only opened with browsers.

In general it would be cool to replace those buttons with long press, to save space and make it more clickable.

**Comment by 1fexd** [comment]
What do you mean by "links only opened with browsers."? Links which can not be handled by any native app? Or links that you, as a user, always open in

**Comment by firefoxlover** [comment]
sorry for the late reply. "Links that cannot be opened by an app" that is.

I always have multiple browsers on my phone and dont know how the behavior would be with only one browser. But I suppose if there is no app, it would automatically use the browser. Now if I have multiple browsers this may be because I always want to decide which one to use. So hiding the "once" button in this specific scenario could be useful.

At the same time maybe hiding it entirely could also be done, to be less specific for this edge case. Afaik "once" can be done by clicking the icon.

**Comment by 1fexd** [comment]
Okay, I understand - probably not a priority at the moment though

Also, kind of related to #281

**Comment by NikunjKhangwal** [comment]
+1 for this
I use two browsers and other apps for different purposes. Choosing app and then clicking just once OR double clicking the app is extra effort. It would be nice if i can select my app with single click right away and it'll open.

**Comment by NikunjKhangwal** [comment]
Cool, thanks man
