### ISSUE TITLE
Add .yml supported urls

### ISSUE THREAD

**Issue by l2eused** [LinkSheet/LinkSheet#299]
### Feature description

Github it using urls that ending up with `.yml` as **template issues**

example template issue: [URLs](https://github.com/1fexd/LinkSheet/issues/new?template=FEATURE-REQUEST.yml)

In **Github mobile** when I want to create new issue with template. It will open external browser. Unfortunately, it seems LinkSheet doesn't support urls *(also Firefox too btw)*

**Is it possible to support `.yml` urls?**

Thanks

> - Android 13
> - Github mobile 1.145.0
> - LinkSheet Version Information:
> Built at (UTC): 2023-12-23 00:19:33
> Flavor: Foss
> Type: nightly
> Commit: 752998a
> Branch: master
> Full identifier: master-752998a-nightly
> Build workflow ID: 7302320960

**Comment by 1fexd** [comment]
Hm, I think this might be a bug in the Github app itself.
