### ISSUE TITLE
Extract URL from shared string

### ISSUE THREAD

**Issue by pressRtowin** [LinkSheet/LinkSheet#348]
### Feature description

Lots of apps append other text to URLs when sharing, and this interferes with LinkSheet's ability to parse them correctly. For example, sharing from the Amazon app results in an indefinite "Loading link" due to the string being shared, for example: 

> Limited-time deal: TP-Link 10GB PCIe Network Card (TX401)-PCIe to 10 Gigabit Ethernet Network Adapter,Supports Windows 11/10/8.1/8/7, Windows Servers 2019/2016/2012 R2, and Linux, Including a CAT6A Ethernet Cable https://a.co/d/2IoCScM

The ability to isolate the URL from the full string (as well as a proper error when no URL is found, instead of the indefinite "Loading link") would be a good feature to include.

**Comment by 1fexd** [comment]
Which build are you running? I can reproduce the infinite loading on an old one from November, but on the latest nightly it errors correctly - will look into better parsing of shared data though.

**Comment by 1fexd** [comment]
Added some fallbacks, if no url could be found then it attempts to parse the text to get the first url
