### ISSUE TITLE
Link handlers not appearing in list until allowed to open links by default in system settings

### ISSUE THREAD

**Issue by pressRtowin** [LinkSheet/LinkSheet#349]
### Bug description

I'm not quite sure what's going on here, but the gist of it is that apps seem to disappear from LinkSheet's list of apps, even when the URL being opened is one that the app can definitely open. I've noticed this in the past but never thought much of it, but two recent experiences put it back on my mind.

Most recently, I noticed that I was unable to open Amazon links with the Amazon app. I tried enabling its "Open supported links" option in the system settings, and noticed that after doing so, it was showing up as an option in LinkSheet when sharing Amazon links. I then disabled the system setting again, and it remained available in LinkSheet. I also tried rebooting my phone afterwards, and it still remained available in LinkSheet. The thought I had was that maybe some kind of "registration" needs to happen for apps to be acknowledged as a link handler, and I thought maybe I had just disabled that setting right away after installing Amazon for the first time, and it never had the chance to register (I did get a new phone within the past year).

However, thinking further, I realized this couldn't be the case, due to my recent experience with another app. Zoho Meeting. When I first installed the app rather recently, I didn't disable the system setting for it, so when I tapped on meeting links that were emailed to me, the app would launch right away. This was the case for a couple months, and I opened many meeting links this way, until I finally went and disabled the system setting for it. Some time after doing so, I was sent another meeting link, and Zoho Meeting would not show up as an option for opening it. This behavior remained for a few weeks, until I got sick of having to manually type in meeting IDs and tried to figure out what was going on. In the process of doing so, I enabled the system setting for it again, and disabled it shortly after, and now, it's showing up in LinkSheet.

I'm not sure if this is an issue with LinkSheet directly, or some weird quirk of Android (that maybe LinkSheet can work around?). Due to the two different cases above, I'm not exactly sure what causes and/or fixes this issue. The second case shows that even if the system setting was enabled for some time, and the app was allowed to handle links directly, that didn't prevent it from not being listed in Linksheet. Both apps were being used regularly too, so it wasn't a case of the apps being put into Deep Sleep due to lack of use.

Any ideas?

### Version

LinkSheet Version Information: Built at (UTC): 2024-03-15 13:56:43 Flavor: Foss Type: nightly Commit: be02728 Branch: master Full identifier: master-be02728-nightly Build workflow ID: 8301028020

### Device

Fold5

### Android version

Android 14 (One UI 6.0)

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Will look into this, but LinkSheet is most probably at fault here

**Comment by 1fexd** [comment]
Managed to reproduce this, but only with Amazon for some reason - are you using Shizuku? and does this also occur for other apps?

**Comment by 1fexd** [comment]
Please try the experiment `experiment_new_query_manager` in the latest nightly build

**Comment by 1fexd** [comment]
May I ask what the url is? Also, do you have the "Parse shared text" feature flag enabled (this one's in `Advanced` -> `Feature flags`)

**Comment by 1fexd** [comment]
This is intended behavior as the app doesn't properly declare itself for link handling.
