### ISSUE TITLE
App crash while sharing link

### ISSUE THREAD

**Issue by NikunjKhangwal** [LinkSheet/LinkSheet#373]
### Bug description

The app randomly crashed for me while sharing link to an app

### Experiments

- [X] I have disabled all experiments

### Version

2024-03-31 15:26:27

### Device

Redmi 9

### Android version

Android 12 (MIUI)

### Application log or crash log

{
"device_basics": {
"android_version": "12",
"locale": "en-US"
},
"device_info": {
"manufacturer": "Xiaomi",
"model": "M2004J19PI",
"fingerprint": "POCO/shiva/shiva:12/SP1A.210812.016/V13.0.2.0.SJRINXM:user/release-keys"
},
"app_info": {
"full_identifier": "master-08818c3-nightly",
"built_at": "2024-03-29 20:49:05",
"commit": "08818c3",
"branch": "master",
"flavor": "Foss",
"type": "nightly",
"workflow_id": "8482489354"
},
"active_experiments": [],
"preferences": [
{
"name": "hide_after_copying",
"value": "true"
},
{
"name": "usage_stats_sorting",
"value": "true"
},
{
"name": "browser_mode",
"value": "AlwaysAsk"
},
{
"name": "selected_browser",
"value": ""
},
{
"name": "in_app_browser_mode",
"value": "AlwaysAsk"
},
{
"name": "selected_in_app_browser",
"value": ""
},
{
"name": "unified_preferred_browser",
"value": "true"
},
{
"name": "in_app_browser_setting",
"value": "UseAppSettings"
},
{
"name": "always_show_package_name",
"value": "false"
},
{
"name": "url_copied_toast",
"value": "true"
},
{
"name": "download_started_toast",
"value": "true"
},
{
"name": "opening_with_app_toast",
"value": "true"
},
{
"name": "resolve_via_toast",
"value": "true"
},
{
"name": "resolve_via_failed_toast",
"value": "true"
},
{
"name": "grid_layout",
"value": "true"
},
{
"name": "use_clear_urls",
"value": "true"
},
{
"name": "fast_forward_rules",
"value": "true"
},
{
"name": "enable_lib_redirect",
"value": "false"
},
{
"name": "follow_redirects",
"value": "false"
},
{
"name": "follow_redirects_local_cache",
"value": "true"
},
{
"name": "follow_redirects_external_service",
"value": "false"
},
{
"name": "follow_only_known_trackers",
"value": "false"
},
{
"name": "follow_redirects_allow_darknets",
"value": "false"
},
{
"name": "dont_show_filtered_item",
"value": "true"
},
{
"name": "preview_url",
"value": "true"
},
{
"name": "enable_downloader",
"value": "false"
},
{
"name": "downloaderCheckUrlMimeType",
"value": "false"
},
{
"name": "enable_ignore_lib_redirect_button",
"value": "false"
},
{
"name": "follow_redirects_timeout",
"value": "15"
},
{
"name": "enable_amp2html",
"value": "false"
},
{
"name": "amp2html_local_cache",
"value": "true"
},
{
"name": "amp2html_external_service",
"value": "false"
},
{
"name": "amp2html_allow_darknets",
"value": "false"
},
{
"name": "enable_request_private_browsing_button",
"value": "true"
},
{
"name": "show_as_referrer",
"value": "false"
},
{
"name": "dev_mode_enabled",
"value": "false"
},
{
"name": "first_run",
"value": "true"
},
{
"name": "show_discord_banner",
"value": "false"
},
{
"name": "use_dev_bottom_sheet",
"value": "false"
},
{
"name": "donate_card_dismissed",
"value": "true"
},
{
"name": "dev_bottom_sheet_experiment",
"value": "true"
},
{
"name": "resolve_embeds",
"value": "false"
},
{
"name": "hide_bottom_sheet_choice_buttons",
"value": "false"
},
{
"name": "last_version",
"value": "1711725545"
},
{
"name": "theme_v2",
"value": "System"
},
{
"name": "theme_material_you",
"value": "true"
},
{
"name": "theme_amoled_enabled",
"value": "false"
},
{
"name": "tap_config_single",
"value": "SelectItem"
},
{
"name": "tap_config_double",
"value": "OpenApp"
},
{
"name": "tap_config_long",
"value": "OpenSettings"
},
{
"name": "expand_on_app_select",
"value": "true"
},
{
"name": "theme",
"value": "0"
}
],
"log": [
{
"type": "Crash",
"time": "2024-03-30T13:24:43.242",
"message": "java.lang.ArrayIndexOutOfBoundsException: length=9; index=9\n\tat java.util.Arrays$ArrayList.get(Arrays.java:4210)\n\tat fe.linksheet.activity.bottomsheet.BottomSheetActivityImpl$NoPreferredAppChoiceButtons$2.P(SourceFile:21)\n\tat fe.linksheet.activity.bottomsheet.button.ChoiceButtonsKt$ChoiceButtons$1$1$1.d(SourceFile:7)\n\tat y0.y.T(SourceFile:13)\n\tat z0.z0$a.f0(SourceFile:134)\n\tat xa.a.K(SourceFile:1)\n\tat c.M0(SourceFile:1)\n\tat zd.i.l(SourceFile:138)\n\tat zd.i.w(SourceFile:45)\n\tat zd.i.K(SourceFile:17)\n\tat z2.g0.P1(SourceFile:51)\n\tat z2.g0.J0(SourceFile:1)\n\tat y0.e.J0(SourceFile:113)\n\tat z2.j.f(SourceFile:167)\n\tat z2.j.f(SourceFile:146)\n\tat z2.j.f(SourceFile:146)\n\tat z2.f.b(SourceFile:30)\n\tat z2.z.a(SourceFile:122)\n\tat f3.r.U(SourceFile:79)\n\tat f3.r.J(SourceFile:224)\n\tat f3.r.dispatchTouchEvent(SourceFile:83)\n\tat android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3184)\n\tat android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2834)\n\tat android.view.View.dispatchPointerEvent(View.java:15165)\n\tat android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6919)\n\tat android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6698)\n\tat android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6135)\n\tat android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6192)\n\tat android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6158)\n\tat android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6323)\n\tat android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6166)\n\tat android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6380)\n\tat android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6139)\n\tat android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6192)\n\tat android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6158)\n\tat android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6166)\n\tat android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6139)\n\tat android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9271)\n\tat android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9211)\n\tat android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9168)\n\tat android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9416)\n\tat android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:280)\n\tat android.os.MessageQueue.nativePollOnce(Native Method)\n\tat android.os.MessageQueue.next(MessageQueue.java:340)\n\tat android.os.Looper.loopOnce(Looper.java:168)\n\tat android.os.Looper.loop(Looper.java:299)\n\tat android.app.ActivityThread.main(ActivityThread.java:8280)\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)\n\tSuppressed: ee.f: [f3.s2@6275150, x1.g@d642f49, v1{Cancelling}@586904e, i1@497656f]\n"
}
]
}

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Did this occur more than once?

**Comment by NikunjKhangwal** [comment]
No, only once

**Comment by 1fexd** [comment]
Very strange, that never have been possible - regardless, I've added additional checks to prevent this in the future.
