### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by shuvashish76** [LinkSheet/LinkSheet#388]
### Feature description

Would you consider publishing the app on F-Droid please?

**Comment by 1fexd** [comment]
Yes, I will submit it to F-Droid once it is polished enough.

**Comment by shuvashish76** [comment]
Please keep the issue open or convert it to a discussion.

**Comment by 1fexd** [comment]
What's left to discuss? Once LinkSheet is polished enough, I'll think about publishing it on F-Droid / other app stores. No need for unnecessary issues or discussions.

**Comment by TPS** [comment]
Old release @ https://apt.izzysoft.de/packages/fe.linksheet .  Is this ready for main F-Drpid, @1fexd?

**Comment by 1fexd** [comment]
No
