### ISSUE TITLE
Nightly APK workflow failing to upload artifacts 

### ISSUE THREAD

**Issue by zt64** [LinkSheet/LinkSheet#393]
Hi
I just noticed that the nightly APK workflow is failing to upload the artifacts and thought I should bring it to your attention 
It says this:
```
No files were found with the provided path: app/build/outputs/apk/$BUILD_FLAVOR/$BUILD_TYPE/*.apk
app/build/outputs/mapping/$BUILD_FLAVOR_TYPE/*.txt. No artifacts will be uploaded.
```
Seems like it stopped working after this commit 3a5bda0

**Comment by 1fexd** [comment]
Thanks, should be fixed via 60a9dbe6ec4d07f28b5a423df718fd98fff3098c
