### ISSUE TITLE
"Resolve embed" Not Handling Translation Sub-path Correctly 

### ISSUE THREAD

**Issue by JasonHK** [LinkSheet/LinkSheet#402]
### Bug description

Both FixTweet and VxTwitter provided and translated embed feature. With a URL like “<https://fxtwitter.com/tsuki_akari/status/1801205214651023650/en>”, it would embed a translated tweet, while redirecting users back to “<https://twitter.com/tsuki_akari/status/1801205214651023650>” upon visiting. But for LinkSheet, it redirect users to “<https://twitter.com/tsuki_akari/status/1801205214651023650/en>”, which in result a 404 error.

### Experiments

- [X] I have disabled all experiments

### Version

master-d285ab5-nightly

### Device

Samsung Galaxy S21

### Android version

Android 14 (One UI 6.0)

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
Thanks, should be fixed now, could you please confirm?

**Comment by JasonHK** [comment]
It works now, thanks!
