### ISSUE TITLE
Link in link finder/handler

### ISSUE THREAD

**Issue by GL513** [LinkSheet/LinkSheet#408]
### Feature description

A toggle to find links inside of links, for example
https://archive.ph/https://www.google.com/maps/

The domain "https://archive.ph" contains "https://www.google.com/maps"

It may also be helpful to include a URL decoder so that way 
"https://google.com"

Doesn't show as
"https%3A%2F%2Fgoogle.com"

And therefore possibly be unreadable by the actual link-in-link handler.

**Comment by 1fexd** [comment]
What's the use case here? Do you encounter links like these often, and if so, would you mind sharing some additional examples? Implementing something like this might prove quite tricky due to encoding, and I don't really see how it's useful, especially since it would detect random links all the time (SSO etc.)

**Comment by GL513** [comment]
> What's the use case here? Do you encounter links like these often, and if so, would you mind sharing some additional examples? Implementing something like this might prove quite tricky due to encoding, and I don't really see how it's useful, especially since it would detect "random" links all the time (SSO etc.)

It was mostly just a thought, not anything major, but I do sometimes come across links that fast forward can't do much with because it might be a captcha site or something, and the link it passes through to is inside the URL.
I'm not too worried about it, and I suppose if this ends up being more useful to others, it would be more low priority

**Comment by 1fexd** [comment]
Thanks for the suggestion and thoughts, appreciate it, but I'll be closing this issue to keep the issue tracker clean
