### ISSUE TITLE
Share link didn't open selected app

### ISSUE THREAD

**Issue by l2eused** [LinkSheet/LinkSheet#419]
### Bug description

When open urls with LinkSheet then
1. press **Share link**
2. share to any apps (ig chat for example)

Should:
Open popup dialog for selected app (open ig app in select chat to share page)

Actual:
Didn't show any popup or action

for acreen recording video, please ask me, I'll send it to you by discord personal chat (because it's content my personal infos)

### Experiments

- [X] I have disabled all experiments

### Version

94f9833 nightly

### Device

Xiaomi 14 (Hyperos)

### Android version

Android 14

### Reproducible on latest nightly build

Yes

**Comment by 1fexd** [comment]
> for acreen recording video, please ask me, I'll send it to you by discord personal chat (because it's content my personal infos)

That would be great! Also include a log if possible
