### ISSUE TITLE
App stopped working altogether after latest nightly update

### ISSUE THREAD

**Issue by NikunjKhangwal** [LinkSheet/LinkSheet#434]
### Bug description

Just updated to latent nightly and app stopped working altogether. Everything i click on a link, Linksheet throws an error

### Experiments

- [X] I have disabled all experiments

### Version

{   "built_at": "2024-08-23 23:37:01",   "flavor": "Foss-nightly",   "version_code": 1724436421,   "version_name": "master-369887e-nightly",   "workflow_id": "10530270846" }

### Device

Poco M2

### Android version

Android 12

### Application log or crash log

`{
  "build_info": {
    "built_at": "2024-08-23 23:37:01",
    "flavor": "Foss-nightly",
    "version_code": 1724436421,
    "version_name": "master-369887e-nightly",
    "workflow_id": "10530270846"
  },
  "device_info": {
    "android_version": "12",
    "manufacturer": "Xiaomi",
    "model": "M2004J19PI"
  },
  "locale": "en-US",
  "fingerprint": "POCO/shiva/shiva:12/SP1A.210812.016/V13.0.2.0.SJRINXM:user/release-keys",
  "active_experiments": [
    "experiment_ui_overhaul",
    "experiment_improved_intent_resolver"
  ],
  "preferences": [
    {
      "name": "hide_after_copying",
      "value": "true"
    },
    {
      "name": "usage_stats_sorting",
      "value": "true"
    },
    {
      "name": "browser_mode",
      "value": "AlwaysAsk"
    },
    {
      "name": "selected_browser",
      "value": "<null>"
    },
    {
      "name": "in_app_browser_mode",
      "value": "AlwaysAsk"
    },
    {
      "name": "selected_in_app_browser",
      "value": "<null>"
    },
    {
      "name": "unified_preferred_browser",
      "value": "true"
    },
    {
      "name": "in_app_browser_setting",
      "value": "UseAppSettings"
    },
    {
      "name": "always_show_package_name",
      "value": "false"
    },
    {
      "name": "url_copied_toast",
      "value": "true"
    },
    {
      "name": "download_started_toast",
      "value": "true"
    },
    {
      "name": "opening_with_app_toast",
      "value": "true"
    },
    {
      "name": "resolve_via_toast",
      "value": "true"
    },
    {
      "name": "resolve_via_failed_toast",
      "value": "true"
    },
    {
      "name": "grid_layout",
      "value": "true"
    },
    {
      "name": "use_clear_urls",
      "value": "true"
    },
    {
      "name": "fast_forward_rules",
      "value": "true"
    },
    {
      "name": "enable_lib_redirect",
      "value": "false"
    },
    {
      "name": "follow_redirects",
      "value": "false"
    },
    {
      "name": "follow_redirects_local_cache",
      "value": "true"
    },
    {
      "name": "follow_redirects_external_service",
      "value": "false"
    },
    {
      "name": "follow_only_known_trackers",
      "value": "false"
    },
    {
      "name": "follow_redirects_allow_darknets",
      "value": "false"
    },
    {
      "name": "follow_redirects_skip_browser",
      "value": "true"
    },
    {
      "name": "dont_show_filtered_item",
      "value": "true"
    },
    {
      "name": "preview_url",
      "value": "true"
    },
    {
      "name": "enable_downloader",
      "value": "false"
    },
    {
      "name": "downloaderCheckUrlMimeType",
      "value": "false"
    },
    {
      "name": "enable_ignore_lib_redirect_button",
      "value": "false"
    },
    {
      "name": "follow_redirects_timeout",
      "value": "15"
    },
    {
      "name": "enable_amp2html",
      "value": "false"
    },
    {
      "name": "amp2html_local_cache",
      "value": "true"
    },
    {
      "name": "amp2html_external_service",
      "value": "false"
    },
    {
      "name": "amp2html_allow_darknets",
      "value": "false"
    },
    {
      "name": "amp2html_skip_browser",
      "value": "true"
    },
    {
      "name": "enable_request_private_browsing_button",
      "value": "true"
    },
    {
      "name": "show_as_referrer",
      "value": "false"
    },
    {
      "name": "dev_mode_enabled",
      "value": "false"
    },
    {
      "name": "first_run",
      "value": "true"
    },
    {
      "name": "show_discord_banner",
      "value": "false"
    },
    {
      "name": "use_dev_bottom_sheet",
      "value": "false"
    },
    {
      "name": "donate_card_dismissed",
      "value": "true"
    },
    {
      "name": "dev_bottom_sheet_experiment",
      "value": "true"
    },
    {
      "name": "resolve_embeds",
      "value": "false"
    },
    {
      "name": "hide_bottom_sheet_choice_buttons",
      "value": "false"
    },
    {
      "name": "telemetry_dialog",
      "value": "true"
    },
    {
      "name": "last_version",
      "value": "1724436421"
    },
    {
      "name": "theme_v2",
      "value": "System"
    },
    {
      "name": "theme_material_you",
      "value": "true"
    },
    {
      "name": "theme_amoled_enabled",
      "value": "false"
    },
    {
      "name": "tap_config_single",
      "value": "OpenApp"
    },
    {
      "name": "tap_config_double",
      "value": "SelectItem"
    },
    {
      "name": "tap_config_long",
      "value": "OpenSettings"
    },
    {
      "name": "expand_on_app_select",
      "value": "true"
    },
    {
      "name": "bottom_sheet_native_label",
      "value": "true"
    },
    {
      "name": "theme",
      "value": "0"
    }
  ],
  "log": [
    {
      "type": "Crash",
      "time": "2024-08-24T04:01:41.999",
      "message": "java.lang.RuntimeException: java.lang.reflect.InvocationTargetException\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)\n\tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1073)\nCaused by: java.lang.reflect.InvocationTargetException\n\tat java.lang.reflect.Method.invoke(Native Method)\n\tat com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)\n\t... 1 more\nCaused by: hd.b: Could not create instance for '[Singleton:'fe.linksheet.experiment.improved.resolver.ImprovedIntentResolver']'\n\tat ii.b.a(SourceFile:194)\n\tat ii.c.a(SourceFile:10)\n\tat ii.c$a.b(SourceFile:10)\n\tat ii.c.b(SourceFile:7)\n\tat oi.b.b(SourceFile:104)\n\tat oi.b.a(SourceFile:162)\n\tat fe.linksheet.experiment.improved.resolver.activity.bottomsheet.ImprovedBottomSheet$special$$inlined$inject$default$1.b(SourceFile:25)\n\tat kc.r.getValue(SourceFile:1)\n\tat fe.linksheet.experiment.improved.resolver.activity.bottomsheet.ImprovedBottomSheet.h(SourceFile:49)\n\tat fe.linksheet.experiment.improved.resolver.activity.bottomsheet.ImprovedBottomSheet$onCreate$1$1.I(SourceFile:29)\n\tat m2.a.I(SourceFile:53)\n\tat e2.c0.a(SourceFile:19)\n\tat y1.c8.a(SourceFile:78)\n\tat y1.x2$b.I(SourceFile:32)\n\tat m2.a.I(SourceFile:53)\n\tat e2.c0.b(SourceFile:19)\n\tat y1.x2.a(SourceFile:282)\n\tat fe.linksheet.ui.ThemeKt$AppTheme$4$1.I(SourceFile:58)\n\tat m2.a.I(SourceFile:53)\n\tat e2.c0.b(SourceFile:19)\n\tat fe.linksheet.ui.ThemeKt$AppTheme$4.I(SourceFile:76)\n\tat m2.a.I(SourceFile:53)\n\tat e2.c0.b(SourceFile:19)\n\tat ci.a.a(SourceFile:122)\n\tat yh.a.a(SourceFile:153)\n\tat fe.linksheet.ui.ThemeKt.b(SourceFile:632)\n\tat fe.linksheet.experiment.improved.resolver.activity.bottomsheet.ImprovedBottomSheet$onCreate$1.I(SourceFile:48)\n\tat m2.a.I(SourceFile:53)\n\tat p3.v1.a(SourceFile:56)\n\tat p3.a$a.I(SourceFile:28)\n\tat m2.a.I(SourceFile:53)\n\tat e2.c0.b(SourceFile:19)\n\tat p3.w1.a(SourceFile:304)\n\tat androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$i.I(SourceFile:32)\n\tat m2.a.I(SourceFile:53)\n\tat e2.c0.b(SourceFile:19)\n\tat androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.a(SourceFile:579)\n\tat androidx.compose.ui.platform.i.I(SourceFile:32)\n\tat m2.a.I(SourceFile:53)\n\tat e2.c0.a(SourceFile:19)\n\tat androidx.compose.ui.platform.j.I(SourceFile:185)\n\tat m2.a.I(SourceFile:53)\n\tat c.N(SourceFile:1)\n\tat e2.o.R(SourceFile:201)\n\tat e2.y.p(SourceFile:31)\n\tat e2.t2.a(SourceFile:25)\n\tat e2.y.c(SourceFile:11)\n\tat androidx.compose.ui.platform.k$a.K(SourceFile:59)\n\tat androidx.compose.ui.platform.a.setOnViewTreeOwnersAvailable(SourceFile:1)\n\tat androidx.compose.ui.platform.k.c(SourceFile:1)\n\tat androidx.compose.ui.platform.k.r(SourceFile:1)\n\tat androidx.lifecycle.t$a.a(SourceFile:23)\n\tat androidx.lifecycle.t.a(SourceFile:229)\n\tat androidx.compose.ui.platform.k$a.K(SourceFile:25)\n\tat androidx.compose.ui.platform.a.onAttachedToWindow(SourceFile:125)\n\tat android.view.View.dispatchAttachedToWindow(View.java:21166)\n\tat android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3561)\n\tat android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3568)\n\tat android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3568)\n\tat android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3568)\n\tat android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3568)\n\tat android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2893)\n\tat android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2389)\n\tat android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9369)\n\tat android.view.Choreographer$CallbackRecord.run(Choreographer.java:1137)\n\tat android.view.Choreographer.doCallbacks(Choreographer.java:920)\n\tat android.view.Choreographer.doFrame(Choreographer.java:834)\n\tat android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1119)\n\tat android.os.Handler.handleCallback(Handler.java:938)\n\tat android.os.Handler.dispatchMessage(Handler.java:99)\n\tat android.os.Looper.loopOnce(Looper.java:210)\n\tat android.os.Looper.loop(Looper.java:299)\n\tat android.app.ActivityThread.main(ActivityThread.java:8280)\n\t... 3 more\nCaused by: hd.b: Could not create instance for '[Singleton:'mg.d']'\n\tat ii.b.a(SourceFile:194)\n\tat ii.c.a(SourceFile:10)\n\tat ii.c$a.b(SourceFile:10)\n\tat ii.c.b(SourceFile:7)\n\tat oi.b.b(SourceFile:104)\n\tat oi.b.a(SourceFile:162)\n\tat fe.linksheet.module.resolver.module.ResolverModuleKt$resolverModule$1$invoke$$inlined$singleOf$default$7.I(SourceFile:187)\n\tat ii.b.a(SourceFile:53)\n\t... 75 more\nCaused by: hi.c: No definition found for type 'java.lang.Integer'. Check your Modules configuration and add missing type and/or qualifier!\n\tat oi.b.b(SourceFile:382)\n\tat oi.b.a(SourceFile:162)\n\tat fe.linksheet.module.unfurler.UnfurlerModuleKt$unfurlerModule$1$invoke$$inlined$singleOf$default$1.I(SourceFile:24)\n\tat ii.b.a(SourceFile:53)\n\t... 82 more\n"
    },
    {
      "type": "I",
      "time": "2024-08-24T04:01:42.041",
      "prefix": "AnalyticsService"
    },
    {
      "type": "D",
      "time": "2024-08-24T04:01:42.041",
      "prefix": "AnalyticsService"
    },
    {
      "type": "D",
      "time": "2024-08-24T04:01:42.041",
      "prefix": "AnalyticsService"
    }
  ]
}`

### Reproducible on latest nightly build

Yes

**Comment by NikunjKhangwal** [comment]
Ok it turned out the improved_intent_resolver experiment was on. I remember not having any experiment on so this probably happened after update. Still keeping the issue open to identify the problem.

**Comment by 1fexd** [comment]
> Ok it turned out the improved_intent_resolver experiment was on. I remember not having any experiment on so this probably happened after update.

Yes, the update has switched this experiment on by default; I've pushed a fix for the crash

**Comment by 1fexd** [comment]
[LinkSheet/nightly@1724479382](https://github.com/LinkSheet/nightly/releases/tag/1724479382)

**Comment by NikunjKhangwal** [comment]
Great work. Thanks

**Comment by NikunjKhangwal** [comment]
Btw is there any plans on releasing update for stable version anytime? Not to rush things, I'm just asking because it's been over a year.
I'm sticking to nightly because a lot of features got added to it which stable doesn't have. But at the same time nightly changes rapidly and always prone to bugs.

**Comment by 1fexd** [comment]
> Btw is there any plans on releasing update for stable version anytime? Not to rush things, I'm just asking because it's been over a year.
I'm sticking to nightly because a lot of features got added to it which stable doesn't have. But at the same time nightly changes rapidly and always prone to bugs.

Yeah, it's been a while - I'll think about what makes the most sense

**Comment by NikunjKhangwal** [comment]
> Yeah, it's been a while - I'll think about what makes the most sense

Any update?
