### ISSUE TITLE
fxYouTube (to bypass age restriction)

### ISSUE THREAD

**Issue by dale2e1** [LinkSheet/LinkSheet#504]
### Feature description

A particularly annoying issue I come across these days when sharing YouTube links to discord is that the player won't start the video due to an age restriction, which can often be for what feels like no reason at all. As a result you have to watch on the YT website which kinda goes against the entire point of embedding the video in the first place. 

Would be cool if there was another service (similar to fxtwitter, etc.) to essentially bypass the age verification within the embed so that all linked videos can actually be played on the platform they were shared to.

**Comment by 1fexd** [comment]
Hm, I'm not sure I quite understand, are you refering to yfxtube.com?

**Comment by dale2e1** [comment]
Oh I didn't know that existed lol I was trying to find something like that yeah

Seems to be down at the moment but I'm guessing yfxtube is probably what I'm looking for

**Comment by 1fexd** [comment]
Great - so how does this relate to LinkSheet?

**Comment by dale2e1** [comment]
I was asking for a youtube fix to be created, but now that I know there is yfxtube, the request is no longer necessary.
